-- MySQL Script generated by MySQL Workbench
-- Ср 03 июл 2019 14:25:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tfdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tfdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tfdb` DEFAULT CHARACTER SET utf8 ;
USE `tfdb` ;

-- -----------------------------------------------------
-- Table `tfdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfdb`.`user` (
  `user_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `role` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tfdb`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfdb`.`project` (
  `project_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `teamlist` VARCHAR(45) NULL,
  `create_stamp` TIMESTAMP NULL,
  PRIMARY KEY (`project_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tfdb`.`case`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfdb`.`case` (
  `case_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `user_created_id` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `size` INT NULL,
  `project_id` INT NOT NULL,
  `create_stamp` TIMESTAMP NULL,
  `update_stamp` TIMESTAMP NULL,
  PRIMARY KEY (`case_id`, `project_id`),
  INDEX `fk_case_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_case_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `tfdb`.`project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tfdb`.`project_user_mapping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfdb`.`project_user_mapping` (
  `project_project_id` INT NOT NULL,
  `user_user_id` INT NOT NULL,
  PRIMARY KEY (`project_project_id`, `user_user_id`),
  INDEX `fk_project_has_user_user1_idx` (`user_user_id` ASC),
  INDEX `fk_project_has_user_project_idx` (`project_project_id` ASC),
  CONSTRAINT `fk_project_has_user_project`
    FOREIGN KEY (`project_project_id`)
    REFERENCES `tfdb`.`project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_has_user_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `tfdb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
